import ProvenHashes.UMASHHighPart13_0
import ProvenHashes.UMASHHighPart13_1
import ProvenHashes.UMASHHighPart13_2
import ProvenHashes.UMASHHighPart13_3
import ProvenHashes.UMASHHighPart13_4
import ProvenHashes.UMASHHighPart13_5
import ProvenHashes.UMASHHighPart13_6
import ProvenHashes.UMASHHighPart13_7
import ProvenHashes.UMASHHighPart13_8
import ProvenHashes.UMASHHighPart13_9
import ProvenHashes.UMASHHighPart13_10
import ProvenHashes.UMASHHighPart13_11
import ProvenHashes.UMASHHighPart13_12
import ProvenHashes.UMASHHighPart13_13
import ProvenHashes.UMASHHighPart13_14
import ProvenHashes.UMASHHighPart13_15
import ProvenHashes.UMASHHighPart13_16
import ProvenHashes.UMASHHighPart13_17
import ProvenHashes.UMASHHighPart13_18
import ProvenHashes.UMASHHighPart13_19
import ProvenHashes.UMASHHighPart13_20
import ProvenHashes.UMASHHighPart13_21
import ProvenHashes.UMASHHighPart13_22
import ProvenHashes.UMASHHighPart13_23
import ProvenHashes.UMASHHighPart13_24
import ProvenHashes.UMASHHighPart13_25
import ProvenHashes.UMASHHighPart13_26

namespace ProvenHashes.UMASH
set_option maxRecDepth 65536
set_option maxHeartbeats 2000000
attribute [local irreducible] highLedgerPrepared13

/-- The full high ledger is the exact sum of the checked row blocks. -/
theorem phenh_high_numerator_13 :
    phenhHighLedgerNumerator 13 = 421127795990564406844057026032 := by
  rw [phenhHighLedger_eq_table, highLedgerData13_correct,
    ledgerSum_eq_fast, highLedgerPrepared13_correct, ledgerFastSum_eq_packed]
  conv_lhs => arg 1; rw [highLedgerPrepared13_partition]
  simp only [ledgerPackedSum_append, highLedgerPart13_0_certificate, highLedgerPart13_1_certificate, highLedgerPart13_2_certificate, highLedgerPart13_3_certificate, highLedgerPart13_4_certificate, highLedgerPart13_5_certificate, highLedgerPart13_6_certificate, highLedgerPart13_7_certificate, highLedgerPart13_8_certificate, highLedgerPart13_9_certificate, highLedgerPart13_10_certificate, highLedgerPart13_11_certificate, highLedgerPart13_12_certificate, highLedgerPart13_13_certificate, highLedgerPart13_14_certificate, highLedgerPart13_15_certificate, highLedgerPart13_16_certificate, highLedgerPart13_17_certificate, highLedgerPart13_18_certificate, highLedgerPart13_19_certificate, highLedgerPart13_20_certificate, highLedgerPart13_21_certificate, highLedgerPart13_22_certificate, highLedgerPart13_23_certificate, highLedgerPart13_24_certificate, highLedgerPart13_25_certificate, highLedgerPart13_26_certificate]
-- CHECKPOINT

end ProvenHashes.UMASH
