import ProvenHashes.UMASHHighPart12_0
import ProvenHashes.UMASHHighPart12_1
import ProvenHashes.UMASHHighPart12_2
import ProvenHashes.UMASHHighPart12_3
import ProvenHashes.UMASHHighPart12_4
import ProvenHashes.UMASHHighPart12_5
import ProvenHashes.UMASHHighPart12_6
import ProvenHashes.UMASHHighPart12_7
import ProvenHashes.UMASHHighPart12_8
import ProvenHashes.UMASHHighPart12_9
import ProvenHashes.UMASHHighPart12_10
import ProvenHashes.UMASHHighPart12_11
import ProvenHashes.UMASHHighPart12_12
import ProvenHashes.UMASHHighPart12_13
import ProvenHashes.UMASHHighPart12_14
import ProvenHashes.UMASHHighPart12_15
import ProvenHashes.UMASHHighPart12_16
import ProvenHashes.UMASHHighPart12_17
import ProvenHashes.UMASHHighPart12_18
import ProvenHashes.UMASHHighPart12_19
import ProvenHashes.UMASHHighPart12_20
import ProvenHashes.UMASHHighPart12_21
import ProvenHashes.UMASHHighPart12_22
import ProvenHashes.UMASHHighPart12_23
import ProvenHashes.UMASHHighPart12_24
import ProvenHashes.UMASHHighPart12_25
import ProvenHashes.UMASHHighPart12_26

namespace ProvenHashes.UMASH
set_option maxRecDepth 65536
set_option maxHeartbeats 2000000
attribute [local irreducible] highLedgerPrepared12

/-- The full high ledger is the exact sum of the checked row blocks. -/
theorem phenh_high_numerator_12 :
    phenhHighLedgerNumerator 12 = 392581668721283187791315876856 := by
  rw [phenhHighLedger_eq_table, highLedgerData12_correct,
    ledgerSum_eq_fast, highLedgerPrepared12_correct, ledgerFastSum_eq_packed]
  conv_lhs => arg 1; rw [highLedgerPrepared12_partition]
  simp only [ledgerPackedSum_append, highLedgerPart12_0_certificate, highLedgerPart12_1_certificate, highLedgerPart12_2_certificate, highLedgerPart12_3_certificate, highLedgerPart12_4_certificate, highLedgerPart12_5_certificate, highLedgerPart12_6_certificate, highLedgerPart12_7_certificate, highLedgerPart12_8_certificate, highLedgerPart12_9_certificate, highLedgerPart12_10_certificate, highLedgerPart12_11_certificate, highLedgerPart12_12_certificate, highLedgerPart12_13_certificate, highLedgerPart12_14_certificate, highLedgerPart12_15_certificate, highLedgerPart12_16_certificate, highLedgerPart12_17_certificate, highLedgerPart12_18_certificate, highLedgerPart12_19_certificate, highLedgerPart12_20_certificate, highLedgerPart12_21_certificate, highLedgerPart12_22_certificate, highLedgerPart12_23_certificate, highLedgerPart12_24_certificate, highLedgerPart12_25_certificate, highLedgerPart12_26_certificate]
-- CHECKPOINT

end ProvenHashes.UMASH
