import ProvenHashes.UMASHHighPart5_0
import ProvenHashes.UMASHHighPart5_1
import ProvenHashes.UMASHHighPart5_2
import ProvenHashes.UMASHHighPart5_3
import ProvenHashes.UMASHHighPart5_4
import ProvenHashes.UMASHHighPart5_5
import ProvenHashes.UMASHHighPart5_6
import ProvenHashes.UMASHHighPart5_7
import ProvenHashes.UMASHHighPart5_8
import ProvenHashes.UMASHHighPart5_9
import ProvenHashes.UMASHHighPart5_10
import ProvenHashes.UMASHHighPart5_11
import ProvenHashes.UMASHHighPart5_12
import ProvenHashes.UMASHHighPart5_13
import ProvenHashes.UMASHHighPart5_14
import ProvenHashes.UMASHHighPart5_15
import ProvenHashes.UMASHHighPart5_16
import ProvenHashes.UMASHHighPart5_17
import ProvenHashes.UMASHHighPart5_18
import ProvenHashes.UMASHHighPart5_19
import ProvenHashes.UMASHHighPart5_20
import ProvenHashes.UMASHHighPart5_21
import ProvenHashes.UMASHHighPart5_22
import ProvenHashes.UMASHHighPart5_23
import ProvenHashes.UMASHHighPart5_24
import ProvenHashes.UMASHHighPart5_25
import ProvenHashes.UMASHHighPart5_26

namespace ProvenHashes.UMASH
set_option maxRecDepth 65536
set_option maxHeartbeats 2000000
attribute [local irreducible] highLedgerPrepared5

/-- The full high ledger is the exact sum of the checked row blocks. -/
theorem phenh_high_numerator_5 :
    phenhHighLedgerNumerator 5 = 562141307222720566191562265040 := by
  rw [phenhHighLedger_eq_table, highLedgerData5_correct,
    ledgerSum_eq_fast, highLedgerPrepared5_correct, ledgerFastSum_eq_packed]
  conv_lhs => arg 1; rw [highLedgerPrepared5_partition]
  simp only [ledgerPackedSum_append, highLedgerPart5_0_certificate, highLedgerPart5_1_certificate, highLedgerPart5_2_certificate, highLedgerPart5_3_certificate, highLedgerPart5_4_certificate, highLedgerPart5_5_certificate, highLedgerPart5_6_certificate, highLedgerPart5_7_certificate, highLedgerPart5_8_certificate, highLedgerPart5_9_certificate, highLedgerPart5_10_certificate, highLedgerPart5_11_certificate, highLedgerPart5_12_certificate, highLedgerPart5_13_certificate, highLedgerPart5_14_certificate, highLedgerPart5_15_certificate, highLedgerPart5_16_certificate, highLedgerPart5_17_certificate, highLedgerPart5_18_certificate, highLedgerPart5_19_certificate, highLedgerPart5_20_certificate, highLedgerPart5_21_certificate, highLedgerPart5_22_certificate, highLedgerPart5_23_certificate, highLedgerPart5_24_certificate, highLedgerPart5_25_certificate, highLedgerPart5_26_certificate]
-- CHECKPOINT

end ProvenHashes.UMASH
